### ISSUE TITLE
Detect NIC's Failure

### ISSUE THREAD

**Issue by sudharsanomprakash** [medik8s/self-node-remediation#110]
Does this operator identity the Node NIC failure and Migrate the VM's to next healthy node?

**Comment by slintes** [comment]
Hi @sudharsanomprakash, there are multiple aspects to the question, let me try to explain:

- In general we try to differentiate between failure detection, and failure handling.
- The main purpose of this self node remediation (SNR) operator is failure handling, by rebooting the failed node and deleting pods and volume attachments afterwards. The reboot will ensure that all workloads stop running, the deletion will accelerate rescheduling of workloads to other nodes.
- For failure detection we offer the Node Health Check (NHC) operator (https://github.com/medik8s/node-healthcheck-operator). It detects unhealthy nodes based on their status conditions, and triggers e.g. SNR.
- However, there are two cases when SNR will reboot the node without NHC: a) the SNR pod on the node stops working. Since the pod armed a watchdog, the watchdog will reboot the node after some time. b) the SNR pod loses network connection to the API server. Note that in these two cases the pods and volume attachments won't be deleted though, so workload rescheduling might be slow.

Circling back to your question: 

1. Does SNR identify NIC failures:

a) without NHC:

- when the failed NIC is for the network which connects the node to the API server: yes, the node will be rebooted, see last item, case b) above.
- otherwise: no

b) with NHC:

- when the NIC failure results in a node condition which triggers NHC (e.g. Ready=False because it is the NIC which connects the node to the API server): yes, the node will reboot, and pods and volume attachments will be deleted
- when there isn't a condition which can be used for NHC (e.g. the NIC isn't used for API server connections, and nothing checks the NIC and updates a node condition accordingly): back to a)

2. Does SNR migrate VMs:

I assume you mean KubeVirt VMs? We don't handle VMs in a special way. But the VM's pod and volume attachment will be deleted. If that wll just start the VM on a healthy node, or if it will trigger an actual live migration, depends on several factors AFAIK. The VM needs to be live migratable in general, and the source VM and node need to be in a state which allows migration... which probably isn't the case when the relevant NIC has a failure. But for details on VMs, please reach out to the KubeVirt folks 🙂 

So, overall we have several "it depends", but I hope this answers your question.

**Comment by mshitrit** [comment]
Hi, small addition to Marc's thorough reply.

> b) the SNR pod loses network connection to the API server.

One caveat is the use case where the other agents lose network connection to the API server, but still have communication between themselves - in that case the agent will assume it's healthy and will not reboot.

Regarding restoring stateful workload, you might want to have a peek at [rook](https://rook.io/) (for k8s) or [ODF](https://www.redhat.com/en/technologies/cloud-computing/openshift-data-foundation) (for OCP), and of course for more info contact KubeVirt folks per Marc's suggestion.

**Comment by sudharsanomprakash** [comment]
@slintes @mshitrit  Thank you for the response. Yes, it for KubevirtVM's. 
I was in understanding that NHC monitors all the Interfaces in the nodes to determine the node health but it makes sense when the NodeConditon is determined based on NIC that connects to API server. 

Since that NodeCondition was mentioned, it brings another question to me, there are No direct NodeCondition for CPU pressure like we have NetworkUnavailable or MemoryPressure. How would NHC react to it? 
Example, What happens when we create CPU stress on a node, Will NHC report status as Ready until the CPU stress causes(might eventually due to stress) other effects like DiskPressure or MemoryPressue?

**Comment by slintes** [comment]
NHC does not monitor any hardware or software on the nodes. It purely looks at the k8s node resource, at the status conditions. You can configure NHC for selecting which conditions should be watched (see https://github.com/medik8s/node-healthcheck-operator/blob/main/docs/configuration.md).
Those conditions have to be set by other controllers. Some are set by core k8s controllers (e.g. Ready, DiskPressure, ...), everything else needs to be set by custom controllers. For the latter https://github.com/kubernetes/node-problem-detector might be worth a look.
