### ISSUE TITLE
`isSoftwareRebootEnabled` doesn't work, node still get annotation for `is-reboot-capable.self-node-remediation.medik8s.io` is `true`

### ISSUE THREAD

**Issue by rockwyc992** [medik8s/self-node-remediation#236]
After setup `isSoftwareRebootEnabled` in `SelfNodeRemediationConfig`, nodes still get annotaion `is-reboot-capable.self-node-remediation.medik8s.io` is `true`

https://github.com/medik8s/self-node-remediation/blob/6c2442db6f97aeb5f6fbd175d875175f2e8c30ed/pkg/utils/annotations.go#L47

I found the source code here. I think it would be `&& (And)` condition between `watchdogInitiated` and `softwareRebootEnabled`, or `softwareRebootEnabled` will never work.

**Comment by rockwyc992** [comment]
Can we disable reboot feature with watchdog enabled ?

We need an options to force disable reboot feature to prevent unexpected rebooting.

**Comment by slintes** [comment]
Reboot is a basic feature of SNR for ensuring that workloads are fenced. Without it, using SNR would not make sense at all. So it can't be disabled.
Reboot is primarily triggered by using a watchdog. Only if initializing a watchdog fails, software reboot is used, if allowed in the config.
So both the annotation and code are correct, because the node can be rebooted by watchdog OR software reboot.

**Comment by slintes** [comment]
closing, feel free to reopen in case things are unclear

/close
